# Generated by Django 6.0.3 on 2026-03-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mfasettings',
            name='failed_2fa_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mfasettings',
            name='lockout_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
